version: "3"

tasks:
  generate-version:
    desc: "Use git describe to generate a tag based on the latest release tag"
    vars:
      SERVICE_RELEASE_TAG: "{{.CLI_ARGS}}"
    cmds:
      - |
        set -euo pipefail
        TAG=$(git describe --tags --always --first-parent --match "{{.SERVICE_RELEASE_TAG}}@[0-9]*.[0-9]*.[0-9]*")
        PREFIX="{{.SERVICE_RELEASE_TAG}}@"
        echo "${TAG#${PREFIX}}"
    silent: true

  generate-version-tag:
    desc: "Combine the image repo with the version tag"
    vars:
      SERVICE_RELEASE_TAG: "{{.CLI_ARGS}}"
      VERSION:
        sh: task -s generate-version -- {{.SERVICE_RELEASE_TAG}}
    cmds:
      - |
        echo "{{.IMAGE_REPO}}:{{.VERSION}}"

  manual-version-tag:
    desc: "Combine the image repo with the input version tag"
    vars:
      VERSION: "{{.CLI_ARGS}}"
    cmds:
      - |
        echo "{{.IMAGE_REPO}}:{{.VERSION}}"

