version: '3'

vars:
  IMAGE_REPO: tinegagideon/seed
  IMAGE_TAG: latest

tasks:
  install-ci:
    desc: Install dependencies
    cmds:
      - echo "No dependencies required"
      
  build-container-image:
    desc: Build container image 
    cmds:
      - docker build -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} .

  test:
    desc: run tests
    cmds:
      - echo "No tests for this service"
