name: Build and Push Containers

on:
  push:
    branches:
      - main
    
    paths:
      - 'vote/**'
      - 'worker/**'
      - 'result/**'
      - 'seed-data/**'

          
    tags:
       - "**@[0-9]*.[0-9]*.[0-9]*" # vote@1.2.3

  workflow_dispatch:
    inputs:
      service: 
        description: "Which Service to build"
        type: choice
        required: true
        options:
          - vote
          - worker 
          - seed-data
          - result
      
      version:
        description: "Tag to use"
        required: false
        type: string


jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.generate-output.outputs.services }}
    steps: 
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0
      - name: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  #v3.0.2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yml

      - name: Generate outputs
        id: generate-output
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]
          then
            echo 'services=["${{ inputs.service }}"]' >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.ref_type }}" == "tag" ]]
          then
            tag="${GITHUB_REF_NAME}"   #vote@1.2.3
            svc="${tag%%@*}"           #vote
            echo "services=[\"$svc\"]" >> "$GITHUB_OUTPUT"
          
          else # push to main
            echo "services=${{ steps.filter.outputs.changes }}" >> "$GITHUB_OUTPUT"
 
          fi
          
          

  build-push-container-images:
    runs-on: ubuntu-24.04
    needs: filter
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != '' }}
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}
    steps: 
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0
        with:
          fetch-depth: 0

      - name: Install Task
        uses: ./.github/actions/setup-dependencies

      - name: Login to Docker Hub Registry
        if: ${{ !env.ACT }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tag
        id: tag
        working-directory: ${{ matrix.service }}
        env:
          INPUT_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.version || '' }}
          SERVICE: ${{ matrix.service }}
        shell: bash
        run: |
          if [[ -n "$INPUT_VERSION" ]]; then
            version=$INPUT_VERSION
          else
            version=$(task utils:generate-version -- "$SERVICE") 
          fi

          echo "version=${version}" >> "$GITHUB_OUTPUT"

      
      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
        with:
          context: ${{ matrix.service }}
          push: ${{ !env.ACT }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ steps.tag.outputs.version}}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha, mode=max